const {handleSearchQuery} = require("./radar")
const { readFileSync } = require("node:fs");
const buildings = {
	'IN-1': 'Innovation Centre Bldg. 1',
	'IN-2': 'Innovation Centre Bldg. 2',
	'EE': 'Engineering East',
	'EG': 'Engineering West',
	'BS': 'Behavioral Sciences Building',
	'AH': 'Dorothy F. Schmidt Arts & Humanities',
	'PA': 'Dorothy F. Schmidt Performing Arts Center',
	'VA': 'Dorothy F. Schmidt Visual Arts Center',
	'GN': 'General Classroom - North',
	'GS': 'General Classroom - South',
	'AL': 'College Of Arts & Letters',
	'BU': 'Phil Smith Hall',
	'ED': 'College Of Education',
	'BC': 'College Of Medicine',
	'NU': 'College Of Nursing',
	'SE': 'Science Building',
	'LL': 'Friedberg Lifelong Learning Center',
	'IS': 'Instructional Services',
	'PS': 'Physical Science Building',
	'SC': 'Sanford Life Sciences Building',
	'SF': 'Schmidt Family Complex For Academic And Athletic Excellence',
	'SP': 'Sean Stein Pavilion',
	'SO': 'Social Science Building',
	'OC': 'Wally Sanger Owl Club Center',
	'KH': 'Barry Kaye Hall',
	'FL': 'Fleming Hall',
	'FW': 'Fleming West',
	'AC': 'Tom Oxley Athletic Center',
	'CE': 'Continuing Education Hall',
	'CM': 'Computer Center',
	'CR': 'Student Activities Center',
	'CU': 'Culture and Society Building',
	'FA': 'MARLEEN & HAROLD FORKAS ALUMNI CENTER',
	'GP': 'Glades Park Towers',
	'HP': 'Heritage Park Towers',
	'IR': 'Indian River Towers',
	'LY': 'S.E. Wimberly Library',
	'OD': 'OFFICE DEPOT CENTER FOR EXECUTIVE EDUCATION',
	'PH': 'Parliament Hall',
	'UN': 'Student Union',
};
console.log(handleSearchQuery("College of Edu", {
    data: JSON.parse(readFileSync("../../data/room_data.json")),
    buildings: Object.values(buildings)
}));
